#!/bin/zsh
# This hook is run after every virtualenv is activated.
export PS1="%{$fg[green]%}%n@%m%{$fg[blue]%}% > "
#PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="%{${fg_bold[white]}%}(env: %{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${fg_bold[white]}%})%{${reset_color}%} $RPROMPT"

